### ISSUE TITLE
DateTimeException thrown from ExecutionTime.nextExecution

### ISSUE THREAD

**Issue by francisdb** [jmrozanec/cron-utils#110]
Cron expression: `0 0 10 ? * SAT-SUN`

```
java.time.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): -1
    at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
    at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
    at java.time.LocalDate.of(LocalDate.java:268)
    at com.cronutils.model.time.generator.BetweenDayOfWeekValueGenerator.isMatch(BetweenDayOfWeekValueGenerator.java:128)
    at com.cronutils.model.time.generator.FieldValueGenerator.generateCandidates(FieldValueGenerator.java:69)
    at com.cronutils.model.time.ExecutionTime.generateDayCandidatesQuestionMarkSupported(ExecutionTime.java:422)
    at com.cronutils.model.time.ExecutionTime.generateDays(ExecutionTime.java:324)
    at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:172)
    at com.cronutils.model.time.ExecutionTime.nextExecution(ExecutionTime.java:126)
```

We should start indicating in the javadocs what kinds of errors a method can throw

**Comment by francisdb** [comment]
We should probably make sure this `-1` magic value is a constant and correctly handled further down:
https://github.com/jmrozanec/cron-utils/blob/f6e99019c884dab0f841412c853834c195ef5ee9/src/main/java/com/cronutils/model/time/ExecutionTime.java#L422

**Comment by espiegel** [comment]
I wonder how come none of the unit tests expose this

**Comment by jmrozanec** [comment]
@francisdb thank you for reporting this. I agree with your observations regarding the -1 propagation and javadocs.

**Comment by francisdb** [comment]
it seems that on `5.0.1` this magic constant was changed to 0 but it still fails to find the next execution

```
java.time.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): 0 (BetweenDayOfWeekValueGenerator.java:123)
[error] com.cronutils.model.time.generator.BetweenDayOfWeekValueGenerator.isMatch(BetweenDayOfWeekValueGenerator.java:123)
[error] com.cronutils.model.time.generator.FieldValueGenerator.generateCandidates(FieldValueGenerator.java:64)
[error] com.cronutils.model.time.ExecutionTime.generateDayCandidatesQuestionMarkSupported(ExecutionTime.java:413)
[error] com.cronutils.model.time.ExecutionTime.generateDays(ExecutionTime.java:316)
[error] com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:164)
[error] com.cronutils.model.time.ExecutionTime.nextExecution(ExecutionTime.java:118)
[error] com.ai.util.CronUtil.validateCronExpression(CronUtil.java:53)
[error] com.ai.util.CronUtilSpec$$anonfun$1$$anonfun$apply$14.apply(CronUtilSpec.scala:45)
[error] com.ai.util.CronUtilSpec$$anonfun$1$$anonfun$apply$14.apply(CronUtilSpec.scala:43)
```

**Comment by jmrozanec** [comment]
@francisdb Thank you for getting back to this. In the release we did not address this issue - will fix it in a future one. Thanks!

**Comment by jmrozanec** [comment]
@francisdb @espiegel Fixed!

**Comment by francisdb** [comment]
Thanks, will try the fix once you have a release out

**Comment by plainswept** [comment]
@jmrozanec Also looking forward to trying this fix. ETA on the next build?

**Comment by jmrozanec** [comment]
@francisdb @espiegel @plainswept The fix was released with version 5.0.5

**Comment by francisdb** [comment]
@jmrozanec I can confirm this is fixed 👍

**Comment by jmrozanec** [comment]
@francisdb Great! Thanks!
