### ISSUE TITLE
Cron Builder/Parser fails on Every X years

### ISSUE THREAD

**Issue by SecurityInsanity** [jmrozanec/cron-utils#148]
The quartz cron builder (and presumably other cron builders) fail when using every N years. With a:

```
java.lang.IllegalArgumentException: Value N not in range [1970, 2099]
        at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.isInRange(ValidationFieldExpressionVisitor.java:152)
        at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:119)
        at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:60)
        at com.cronutils.model.field.expression.FieldExpression.accept(FieldExpression.java:42)
        at com.cronutils.builder.CronBuilder.addField(CronBuilder.java:81)
        at com.cronutils.builder.CronBuilder.withYear(CronBuilder.java:45)
```

Some reproduction code is:

```
CronBuilder.cron(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ)).withDoM(FieldExpressionFactory.on(1))
                        .withDoW(FieldExpressionFactory.questionMark())
                        .withYear(FieldExpressionFactory.every(4))
                        .withMonth(FieldExpressionFactory.on(0))
                        .withHour(FieldExpressionFactory.on(0))
                        .withMinute(FieldExpressionFactory.on(0))
                        .withSecond(FieldExpressionFactory.on(0))
```

The result I'm looking for is: Every N years on the first month/first hour/first second something runs.

**Comment by SecurityInsanity** [comment]
I also seem to be running into this when trying to parse a cron manually:

```ZonedDateTime zdt = ZonedDateTime.now();
                int year = zdt.getYear();
                CronParser cp = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
                Cron cron;
                try {
                    cron = cp.parse(String.format("0 0 0 1 0 ? %d/%d", year, 4));
                } catch (Exception e1) {
                    System.err.println(e1.getMessage());
                }```

**Comment by jmrozanec** [comment]
@meincs the contributed code does not seem to fix #148 Please note the test at CronParserQuartzIntegrationTest#testEveryXYears() Thanks!

**Comment by meincs** [comment]
Problem was due to a bug in the test. Issue should be fixed and can be closed now.

**Comment by jmrozanec** [comment]
@meincs you are right! Thanks for contributing the fix! 😄
