### ISSUE TITLE
Backport to Java7/Android

### ISSUE THREAD

**Issue by curioustechizen** [jmrozanec/cron-utils#157]
For an Android app, I had a need to parse a Cron expression and determine the previous/next execution date based on this expression. I came across this library but then realized it relies on JSR310 which was introduced in Java 8 and does not work with Android.

I forked the library and was able to make it work on Android in 2 steps:

## Step 1: Make it work with Java 7
  1. Use  [threetenbp](https://github.com/ThreeTen/threetenbp) which is a backport of JSR310
  2. Search-and-replace all occurrences of `java.time` with `org.threeten.bp`
  3. Use [retrolambda](https://github.com/orfjackal/retrolambda) to be able to use `java.util.function.Function` and the lambdas in pre-Java 8

With this, I was able to successfully run all cron-util tests with a target of Java 7

## Step 2: Make it work on Android
Here I started off with some tests for my own use case (parse a Cron expression and get the next/previous execution times), but I made them Android tests (i.e., run on an emulator). For this. I had to make some more changes in my app/tests

  1. Add [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP) which is an Android extension to threetenbp.
  2. Initialize ThreeTenABP in my test [like this](https://github.com/JakeWharton/ThreeTenABP/blob/master/threetenabp/src/androidTest/java/com/jakewharton/threetenabp/AndroidThreeTenTest.java#L18). If you use it in an app, you will still have to init it in your `Application` sub-class.
  3. Add a dependency on an *implementation* of SL4J. I used this one but any which works for you will do.

`compile 'eu.lp0.slf4j:slf4j-android:1.7.22-0'`

With these changes, I was able to run my app-specific tests successfully on Android.

# Next steps

I left it at that because I am not sure how the maintainers would like to proceed with this. There are open questions like
  - Do you want to support Android in the first place?
  - If so, would you like to use JSR310 for Java8 targets and use the backport for older targets? Basically generate multiple versions of the library from the same code-base with multiple targets
  - Would you rather do some runtime shenanigans to detect if JSR310 is on the classpath and use that and fall back to the backport otherwise (don't even know if this is possible!)
  - How would you like to approach the tests? For the Android target, It makes sense to run all the existing (408, at the time of this writing) tests on an emulator to make sure everything is compatible.

**Comment by jmrozanec** [comment]
@curioustechizen Thank you for such a detailed suggestion. Definitively we want to support Android. I think the best way would be to create a branch for that and release the version with the 'android' binary classifier. As for the tests, an emulator would be best. I have not much experience with it, but we can dig into it. 

We just created the ['android' branch](https://github.com/jmrozanec/cron-utils/tree/android). You are welcome to push the changes you introduced and tested locally. Please lead the effort, and let us know how we can help with this.

Thanks!

**Comment by jmrozanec** [comment]
@curioustechizen we just pushed changes for 5+ issues we solved. Perhaps would be good to sync 'android' branch with master if working on it, to avoid merging too many changes later. Best!

**Comment by curioustechizen** [comment]
@jmrozanec I will have to do some cleanup on our fork (since I have now converted the project to Gradle and done some more changes to make it work with Android Studio). I will see what best I can do during the coming week.

One question though - are you proposing that we have 2 separate branches and that the android branch should always pull in the changes from develop/master whenever there are bug fixes in develop/master?

I think that might become painful in the long run. It might be a good idea to explore build script automation to "convert" the Java8 version to Android version (if you the steps I mentioned above, it seems to be an automatable process).

**Comment by jmrozanec** [comment]
@curioustechizen thanks! As long as we can build both binaries in same branch, we can do that in master. Let's port everything at android and merge back to master when is ready together with the proper build settings.

**Comment by curioustechizen** [comment]
While I was working further on this, I realized that cron-utils uses `java.util.Optional` which is not available on Android prior to API 24. I could replace it with Guava's `Optional<T>` but there are some incompatibilities between the two. For example, I cannot find how to use `Optional.empty()` in Guava's Optional.

Now this makes me wonder how did I get things of work on Android in the first place. I will have to revisit my Android tests to figure out what I did there.

In the meantime any suggestions on a replacement for `Optional.empty()`?

**Comment by curioustechizen** [comment]
While I was working further on this, I realized that cron-utils uses `java.util.Optional` which is not available on Android prior to API 24. I could replace it with Guava's `Optional<T>` but there are some incompatibilities between the two. For example, I cannot find how to use `Optional.empty()` in Guava's Optional.

You can see the WIP [here](https://github.com/curioustechizen/cron-utils/tree/experiment/migrate-android).

Now this makes me wonder how did I get things of work on Android in the first place. I will have to revisit my Android tests to figure out what I did there.

In the meantime any suggestions on a replacement for `Optional.empty()`?

**Comment by jmrozanec** [comment]
@curioustrchizen sure! First of all, great progress! Thanks! 

We took out Guava when JDK support for Functions was added, since previously we found [some complaints at Stackoverflow about that dependency being too heavy](http://stackoverflow.com/questions/23835171/cronexpression-parsing-into-java-date). Once we upgraded JDK we also used the other available features: optionals, etc.

Our first goal is a full working Android compatible version. We can use the Guava optional and instead of empty(), you may use the [Optional.absent](https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained#optional)
If the only feature we need from Guava is that, we may avoid the whole dependency by copying the Optional classes to our project. The Apache license allows that, and remove them later, when Android supports a newer JDK.

What are your thoughts on this? Would that solve the issue? Best!

**Comment by curioustechizen** [comment]
Well on the Android side most devs use proguard to eliminate unused code anyway so I don't think it is that big a deal to use Guava. I think we would eventually need Guava anyway for things like `Preconditions`, so maybe it is okay to keep it there.

By the way I just realized that the `Optional` feature was added in a recent commit on master and that I just merged into android branch. The last time I tried running on Android, the Optional was not used. That explains why I could run it. For a moment I thought I had gone insane :stuck_out_tongue: 

Thanks for pointing out `Optional.absent()`. I will experiment with it and see how that goes.

**Comment by jmrozanec** [comment]
@curioustechizen great! Thanks for pointing to ProGuard :) We should include that for future releases, for optimized binaries.

**Comment by curioustechizen** [comment]
There is quite a bit of [progress](https://github.com/curioustechizen/cron-utils/commit/6412955d112a370fbec4ce043eb612771c632a87), but we are still not in a production-ready state yet. I guess we'll have to wait till next weekend.

Here are a summary of pending problems:
  - One failing unit test
  - One failing integration test
  - Tests run from Android Studio but gradle cannot find tests to run
  - Travis config has to be added

**Comment by jmrozanec** [comment]
@curioustechizen perfect! :)

**Comment by jmrozanec** [comment]
@curioustechizen do we have any updates on this? We checked the following:
- no failing tests if running with Maven or Gradle
- we found that Gradle finds all tests. If were previously run and not modified, are not re-run. You can force a re-run using: ./gradlew cleanTest test
- let's figure out the Travis changes when all this is in place.

Please let us know if this is useful and how can we help in order to merge back to master asap.
Thanks!

**Comment by curioustechizen** [comment]
@jmrozanec Unfortunately this has taken lower priority and I haven't gotten around to completing it. I will do it sometime this week.

**Comment by jmrozanec** [comment]
@curioustechizen thank you! We look forward to release it! Best!

**Comment by curioustechizen** [comment]
@jmrozanec Would like to point out that the working branch in my fork is [experiment/migrate-android](https://github.com/curioustechizen/cron-utils/commits/experiment/migrate-android). This is the one where all the Android related changes are. This is the branch where I see some failing tests.

It will still be a couple of days before I can look into this but if you can give it a shot it would be great.

**Comment by jmrozanec** [comment]
@curioustechizen sure. Can you describe the executed goals? We find no failures executing mvn clean install or the gradle goals described above - we must be missing something. Thanks!

**Comment by curioustechizen** [comment]
@jmrozanec I just tried running all the test in src/androidTest folder in Android Studio (these tests need to be run on an Android emulator/device). One of those tests fail. Similarly, I ran the tests in src/test (for these you don't need an emulator). One of these also failed.

Running from the command line, gradle could not find any tests but I did not get the time to look into this in detail.

**Comment by curioustechizen** [comment]
@jmrozanec Some more info:

I think there was some problem with the particular emulator I was using. It was an API 22 emulator. I then created a new one with Android API 19 and now I can get gradle to run the instrumentation tests.

When I run `./gradlew connectedAndroidTest` I see one failure - a StackOverflow in ExecutionTimeQuartzIntegrationTest.nextExecutionNotFail.

```
java.lang.StackOverflowError
at org.threeten.bp.LocalTime.ofNanoOfDay(LocalTime.java:374)
at org.threeten.bp.LocalDateTime.plusWithOverflow(LocalDateTime.java:1410)
at org.threeten.bp.LocalDateTime.plusSeconds(LocalDateTime.java:1180)
at org.threeten.bp.zone.ZoneOffsetTransition.getDateTimeAfter(ZoneOffsetTransition.java:232)
at org.threeten.bp.zone.StandardZoneRules.findOffsetInfo(StandardZoneRules.java:393)
at org.threeten.bp.zone.StandardZoneRules.getOffsetInfo(StandardZoneRules.java:339)
at org.threeten.bp.zone.StandardZoneRules.getValidOffsets(StandardZoneRules.java:319)
at org.threeten.bp.ZonedDateTime.ofLocal(ZonedDateTime.java:342)
at org.threeten.bp.ZonedDateTime.resolveLocal(ZonedDateTime.java:586)
at org.threeten.bp.ZonedDateTime.plusMonths(ZonedDateTime.java:1516)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:178)
at com.cronutils.model.time.ExecutionTime.nextExecution(ExecutionTime.java:121)
at com.cronutils.model.time.ExecutionTimeQuartzIntegrationTest.nextExecutionNotFail(ExecutionTimeQuartzIntegrationTest.java:562)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

There is another failure in the **unit** tests when I run from Android Studio, but when I run the same from Gradle it all passes. So I think we can ignore that.

The latest commits on [experiment/migrate-android](https://github.com/curioustechizen/cron-utils/commits/experiment/migrate-android) branch reflect this state.

Could you look into the StackOverflow error mentioned above? If that is resolved I think we can merge it.

**Comment by jmrozanec** [comment]
@curioustechizen will take a look at it. Thanks!

**Comment by jmrozanec** [comment]
@curioustechizen we have a solution for this - the tests are passing. I cannot fork your fork :) but attached we provide the patch. May we ask you to merge it on your fork, validate if is ok and send a pull request? Thanks!

[0001-Issue-157-bugfix-refactor-how-next-previous-executio.patch.zip](https://github.com/jmrozanec/cron-utils/files/906765/0001-Issue-157-bugfix-refactor-how-next-previous-executio.patch.zip)

**Comment by jmrozanec** [comment]
@curioustechizen we just merged the PR back to android branch! Now we are looking how to deploy the new artifact. We added the required dependencies on pom.xml too. We have two possible paths:
- create a classifier for android
- release a single binary that targets all

The second one is preferred, but we still need to test if we can run the library anywhere without adding the [com.jakewharton.threetenabp:threetenabp:1.0.3](http://stackoverflow.com/questions/38281808/threeten-backport-error-on-android-zonerulesexception-no-time-zone-data-files) dependency, which is required to run some tests due to missing timezone files ...
If you have any thoughts on this, will be very welcome!
Thank you again for the initiative and effort put on this!

**Comment by curioustechizen** [comment]
@jmrozanec This is a tough one :)

I actually revisited the code and I think there are no Android-specific dependencies for the **library** itself in the android branch. I do see the dependency on `com.jakewharton.threetenabp:threetenabp:1.0.3` but that seems to be unnecessary. It is only required for running the _android tests_ but not for the library itself. Instead, you can probably do
```groovy
compile 'org.threeten:threetenbp:1.3.2'
androidTestCompile ("com.jakewharton.threetenabp:threetenabp:1.0.5") {
    exclude (group: 'org.threeten', module: 'threetenbp')
}
```

What I'm trying to say is I think it is possible to turn the `android` branch into the main branch from where you create a single release binary (a JAR) that targets all platforms. You will still need to run the `androidTest/` tests on an Android emulator and continue running the other tests on a desktop JVM. This setup is possible on Travis.

But don't take my word for it. It is a good idea to research how other libraries approach this problem. Also, note that with this approach, all future contributors will have to make sure not to use Java8 features like streams.

**Comment by jmrozanec** [comment]
@curioustechizen Thank you for the quick response! Yes, is a though one - only for the best ;)
You are right about pointing out the issue about using other JDK8 features. Perhaps we should maintain both branches and release a 'default' and 'android' version. Will do some research on this.
 
I am not familiar configuring Travis for Android and also lack of criteria, to know which versions we should target for best compatibility/wide audience. It would be great if you have some time to help with that, or/and point to some libraries where we could get ideas how to deal with the release management :) Thanks!

**Comment by jmrozanec** [comment]
@curioustechizen we just checked the 'android' version at another project and works ok - no other imports are required. If you agree, we can merge to master. Please confirm - and we perform the merge. Thanks!

**Comment by curioustechizen** [comment]
If you have verified that it runs fine on desktop Java then I am fine to merge it into master.

Unfortunately I will not be able to look into the travis configuration for running automated tests for a couple of weeks.

**Comment by jmrozanec** [comment]
@curioustechizen sure. Just found out that we cannot setup a Java and Android language at the same time for Travis. I am thus deleting the Gradle project files at 'master' and will keep them at the 'android' branch, which will hold the Android Travis configuration as well. The deployed jar will still be a single one: the one from 'master', but the builds at 'android' should help us address issues early. Thank you for the help!

**Comment by jmrozanec** [comment]
@curioustechizen version 6.0.0 was released with this changes!
