### ISSUE TITLE
Default Cron4j definition is not allowing L for last day of month

### ISSUE THREAD

**Issue by pangyikhei** [jmrozanec/cron-utils#204]
Release: 6.0.1

According to the [SchedulingPattern](http://www.sauronsoftware.it/projects/cron4j/api/it/sauronsoftware/cron4j/SchedulingPattern.html) in cron4j, 

> The special value L can be used to recognize the last day of month.

Test method:
```
@Test
public void testLastDayOfMonth() {
    String cronExpr = "* * L * *";
    cron4jParser.parse(cronExpr);
}
```

Expected result:
The CronParser should accept a cron4j pattern with the character L

Actual result:
```
java.lang.IllegalArgumentException: Failed to parse '* * L * *'. Invalid chars in expression! Expression: L Invalid chars: L
...
Caused by: java.lang.IllegalArgumentException: Invalid chars in expression! Expression: L Invalid chars: L
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:76)
	at com.cronutils.model.field.expression.FieldExpression.accept(FieldExpression.java:44)
	at com.cronutils.model.Cron.validate(Cron.java:92)
	at com.cronutils.parser.CronParser.parse(CronParser.java:96)
	... 24 more
```

**Comment by jmrozanec** [comment]
@pangyikhei Thank you for reporting this. We would greatly appreciate a PR with this test cases. Thanks!

**Comment by jmrozanec** [comment]
@pangyikhei thank you for providing a bugfix for this! 😄
