### ISSUE TITLE
Issue with isMatch()

### ISSUE THREAD

**Issue by hellorameshus1** [jmrozanec/cron-utils#218]
I am using CronUtil and trying to build custom CronDefinition as below, then I am trying to match whether given time matches the expression. However I am getting exception while doing same. Please find code sample given below:

CronDefinition cronDefinition = defineCron().withMinutes().and()
            .withHours().and()
            .withDayOfWeek()
            .optional()
            .and()
            .instance();
CronDescriptor descriptor = CronDescriptor.instance(Locale.US);
CronParser parser = new CronParser(cronDefinition);
Cron cron = parser.parse(cronExpression);
ExecutionTime executionTime = ExecutionTime.forCron(cron);
boolean isMatch = executionTime.isMatch(ZonedDateTime.now());

Inputs: cronExpression: "0-59 7-16 MON-FRI"
Output: getting exception, expected true/false.

**Comment by jmrozanec** [comment]
@hellorameshus1 thank you for reporting this! We will review ASAP and provide an answer. Best!

**Comment by hellorameshus1** [comment]
Please find below exception trace for further understanding about issue:

Invalid value for DayOfMonth (valid values 1 - 28/31): 0
org.threeten.bp.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): 0
	at org.threeten.bp.temporal.ValueRange.checkValidValue(ValueRange.java:278)
	at org.threeten.bp.temporal.ChronoField.checkValidValue(ChronoField.java:557)
	at org.threeten.bp.LocalDate.of(LocalDate.java:238)
	at com.cronutils.model.time.generator.BetweenDayOfWeekValueGenerator.isMatch(BetweenDayOfWeekValueGenerator.java:128)
	at com.cronutils.model.time.generator.FieldValueGenerator.generateCandidates(FieldValueGenerator.java:64)
	at com.cronutils.model.time.ExecutionTime.generateDayCandidatesUsingDoW(ExecutionTime.java:608)
	at com.cronutils.model.time.ExecutionTime.generateDays(ExecutionTime.java:387)
	at com.cronutils.model.time.ExecutionTime.potentialPreviousClosestMatch(ExecutionTime.java:293)
	at com.cronutils.model.time.ExecutionTime.previousClosestMatch(ExecutionTime.java:284)
	at com.cronutils.model.time.ExecutionTime.lastExecution(ExecutionTime.java:466)
	at com.cronutils.model.time.ExecutionTime.isMatch(ExecutionTime.java:495)
	at com.tdameritrade.trading.grid.util.CronUtils.validateExecutionTime(CronUtils.java:71)
	at com.tdameritrade.trading.grid.util.CronUtilsTest.testValidateExecutionTime(CronUtilsTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.experimental.theories.Theories$TheoryAnchor$2.evaluate(Theories.java:274)
	at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:232)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:218)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:204)
	at org.junit.experimental.theories.Theories$TheoryAnchor.evaluate(Theories.java:187)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by minidmnv** [comment]
Well I think that You've just provided not enough informations to parser. Regarding to [Cron Expressions](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm#CIHBEEFA) Seconds, Minutes, Hours, Day of month, Month and Day of week are required fields. 

I think, that problem here is to make exception (or message) more user friendly. If I'm correct I can do this.

**Comment by jmrozanec** [comment]
@minidmnv thank you for reaching out! The issue is that the isMatch() method should return true/false, while the validate() expression returns an exception. You could provide a better exception message, but the acceptance criteria would be a test with the code provided above, which passes without throwing an exception. Please let us know if further clarifications are needed. Thanks!

**Comment by minidmnv** [comment]
Ohh ok, my bad. You can assign me, I'll do that.

**Comment by jmrozanec** [comment]
@minidmnv Great! Thanks!

**Comment by jmrozanec** [comment]
@hellorameshus1 solved by @minidmnv Thanks!
