### ISSUE TITLE
Getting java.lang.NoSuchMethodError: org.joda.time.DateTime.withDayOfWeek

### ISSUE THREAD

**Issue by kauspatel** [jmrozanec/cron-utils#221]
Hi All,
I am getting java.lang.NoSuchMethodError: org.joda.time.DateTime.withDayOfWeek while parsing "0 0 12 ? * MON-FRI *" cron expression. It works if I set cron expression for minutes or Hours. But stops working for Days or Month or Year.
Code Snippet:
        String description="";
        try{
        CronDefinition cronDefinition =
        CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        CronParser parser = new CronParser(cronDefinition);
        CronDescriptor descriptor = CronDescriptor.instance(Locale.ENGLISH);
            Cron quartzCron=parser.parse(cronExp);
        description = descriptor.describe(quartzCron);
        }catch(Exception e){
            e.printStackTrace();
        }
I am using Java 7u95 and have other limitations in using Java 8.
Following are the versions of Jar which I am using:
cron-utils-4.1.3.jar
commons-lang3-3.3.2.jar
guava-17.0.jar
htime-1.0.0.jar
joda-time-2.9.9.jar
slf4j-api-1.7.7.jar

Regards,
Kaustubh

**Comment by jmrozanec** [comment]
@kauspatel thank you for reporting this! May we ask you to send a PR with the test case? Thanks!

**Comment by kauspatel** [comment]
Adding trace:
Exception in thread "main" java.lang.NoSuchMethodError: org.joda.time.DateTime.withDayOfWeek(I)Lorg/joda/time/DateTime;
	at com.cronutils.descriptor.DescriptionStrategyFactory$1.apply(DescriptionStrategyFactory.java:35)
	at com.cronutils.descriptor.DescriptionStrategyFactory$1.apply(DescriptionStrategyFactory.java:32)
	at com.cronutils.descriptor.DescriptionStrategy.nominalValue(DescriptionStrategy.java:98)
	at com.cronutils.descriptor.DescriptionStrategy.describe(DescriptionStrategy.java:166)
	at com.cronutils.descriptor.DescriptionStrategy.describe(DescriptionStrategy.java:76)
	at com.cronutils.descriptor.DescriptionStrategy.describe(DescriptionStrategy.java:57)
	at com.cronutils.descriptor.NominalDescriptionStrategy.describe(NominalDescriptionStrategy.java:61)
	at com.cronutils.descriptor.CronDescriptor.describeDayOfWeek(CronDescriptor.java:124)
	at com.cronutils.descriptor.CronDescriptor.describe(CronDescriptor.java:63)

**Comment by kauspatel** [comment]
@jmrozanec Do I need to use another set of the library. How can I resolve this issue?

**Comment by pangyikhei** [comment]
It looks like you are using cron-utils 4.1.3. Can you upgrade to the latest version (6.0.2)?

**Comment by kauspatel** [comment]
@pangyikhei  I am not sure whether version 6.0.2 is supported with Java 7u95. I have some restriction to use Java 8.

**Comment by pangyikhei** [comment]
@kauspatel I think 6.0.2 should support Java 7, since it's actually using a JSR-310 backport instead of the Java 8 time classes.

**Comment by kauspatel** [comment]
@pangyikhei I am getting "java.lang.NoSuchMethodError: java.util.Stream" when I am using cron-utils 6.0.2. Java stream is part of java 8 and I can't use java 8.

**Comment by pangyikhei** [comment]
I set my editor to Java 7 language level and fixed all of the compile time errors found in the new commit. I'm not sure if that is required when used as a dependency for the lambda expressions (if the bytecode generated from Java 8 code is compatible with JRE 7). Though I suppose at least the usage of the List.sort method could throw an error for Java 7 users.
