### ISSUE TITLE
Use of ZoneDateTime.now() in Logger.trace()

### ISSUE THREAD

**Issue by SvenssonWeb** [jmrozanec/cron-utils#256]
https://github.com/jmrozanec/cron-utils/blob/a8501749cd43ce7f832ee4ba2d921686bf066976/src/main/java/com/cronutils/model/time/generator/EveryFieldValueGenerator.java#L52

This causes issues when using custom Clock, and never setting a Time Zone.
Since it is buried inside the code, only setting public values can change this.
Is this Log statement necessary, or can we just remove it?

Also, since this statement do not have a log.isTraceEnabled() guard, the expressions will be converted to strings and cause a computational hit, even when log level is lower.

See Stacktrace below:

    org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered

	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:176)
	at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:133)
	at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
	at org.threeten.bp.ZoneId.of(ZoneId.java:357)
	at org.threeten.bp.ZoneId.of(ZoneId.java:285)
	at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:244)
	at org.threeten.bp.Clock.systemDefaultZone(Clock.java:137)
	at org.threeten.bp.ZonedDateTime.now(ZonedDateTime.java:168)
	at com.cronutils.model.time.generator.EveryFieldValueGenerator.<init>(EveryFieldValueGenerator.java:52)
	at com.cronutils.model.time.generator.FieldValueGeneratorFactory.forCronField(FieldValueGeneratorFactory.java:40)
	at com.cronutils.model.time.ExecutionTimeBuilder.forMinutesMatching(ExecutionTimeBuilder.java:54)
	at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:107)

**Comment by SvenssonWeb** [comment]
Given that this is the only `ZonedDateTime.now()` statement I could find. Removing it would add more compliance to the rest of the code base.

**Comment by jmrozanec** [comment]
@SvenssonWeb we agree on that. Please send a PR and will merge asap. Thanks! 😄

**Comment by jmrozanec** [comment]
@SvenssonWeb merged!
