### ISSUE TITLE
String constants (months and day of week) not working as expected

### ISSUE THREAD

**Issue by michaelknigge** [jmrozanec/cron-utils#27]
Hi,

the string constants are not working as expected. One can code "MON-FRI" for the day of the week, but "MON" for "just on mondays" doesn't work.

Same issue for the month. "JAN-FEB" is ok, but "JAN" for just january doesn't work, too.

Furthermore, some months doenst work with "from-to". With cron definition QUARTZ I've tried to pass "0 0 0 * JUL-AUG * *" - but this results in a 

    Exception in thread "main" java.lang.IllegalArgumentException: Values must not be empty
	at org.apache.commons.lang3.Validate.notEmpty(Validate.java:300)
	at com.cronutils.model.time.TimeNode.<init>(TimeNode.java:26)
	at com.cronutils.model.time.ExecutionTimeBuilder.forMonthsMatching(ExecutionTimeBuilder.java:83)
	at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:83)
	at mk.test.Main.testCronUtilsOwnDefinition(Main.java:42)
	at mk.test.Main.main(Main.java:21)

My fault?

Thanks, Michael

**Comment by jmrozanec** [comment]
@michaelknigge Thank you for reporting this.
I checked the issues you mention. 
I was not able to reproduce the issues related to month values. I created tests for them, but they passed without any code change.
The values related to days of week produced the error you mention. I created the corresponding tests, and a code fix to get it right. 
Thanks!

**Comment by michaelknigge** [comment]
Here is the code I've used to produce the Exception:

      final String cronExpression = "0 0 0 * JUL-AUG * *";

      final CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
      final CronValidator validator = new CronValidator(cronDefinition);
      System.out.println("isValid:" + validator.isValid(cronExpression));

      final CronParser parser = new CronParser(cronDefinition);
      final Cron cron = parser.parse(cronExpression);

      final ExecutionTime executionTime = ExecutionTime.forCron(cron);

When executing this I'll get a

    Exception in thread "main" java.lang.IllegalArgumentException: Values must not be empty
	at org.apache.commons.lang3.Validate.notEmpty(Validate.java:300)
	at com.cronutils.model.time.TimeNode.<init>(TimeNode.java:26)
	at com.cronutils.model.time.ExecutionTimeBuilder.forMonthsMatching(ExecutionTimeBuilder.java:83)
	at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:83)
	at mk.test.Main.testCronUtilsOwnDefinition(Main.java:42)
	at mk.test.Main.main(Main.java:21)

If I change 
     final String cronExpression = "0 0 0 * JUL-AUG * *";
to
     final String cronExpression = "0 0 0 * JUL * *";

the cron expression can also not be evaluated:

    Exception in thread "main" java.lang.IllegalArgumentException: Special char L not supported!
	at com.cronutils.model.field.constraint.FieldConstraints.validateSpecialCharAllowed(FieldConstraints.java:132)
	at com.cronutils.parser.field.FieldParser.parseOn(FieldParser.java:136)
	at com.cronutils.parser.field.FieldParser.parse(FieldParser.java:51)
	at com.cronutils.parser.field.CronParserField.parse(CronParserField.java:68)
	at com.cronutils.parser.CronParser.parse(CronParser.java:88)
	at mk.test.Main.testCronUtilsOwnDefinition(Main.java:40)
	at mk.test.Main.main(Main.java:21)

Similar example:

      final String cronExpression = "0 0 0 * * MON *";

      final CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
      final CronValidator validator = new CronValidator(cronDefinition);
      System.out.println("isValid:" + validator.isValid(cronExpression));

      final CronParser parser = new CronParser(cronDefinition);
      final Cron cron = parser.parse(cronExpression);

will throw

    Exception in thread "main" java.lang.IllegalArgumentException: Invalid value. Expected some integer, found MON
	at com.cronutils.parser.field.FieldParser.mapToIntegerFieldValue(FieldParser.java:149)
	at com.cronutils.parser.field.FieldParser.parseOn(FieldParser.java:138)
	at com.cronutils.parser.field.FieldParser.parse(FieldParser.java:51)
	at com.cronutils.parser.field.CronParserField.parse(CronParserField.java:68)
	at com.cronutils.parser.CronParser.parse(CronParser.java:88)
	at mk.test.Main.testCronUtilsOwnDefinition(Main.java:40)
	at mk.test.Main.main(Main.java:21)

But the cron expression "0 0 0 * * MON-FRI *" works.


Bye,
Michael

**Comment by jmrozanec** [comment]
@michaelknigge Yes, you are right. Everything works, except for ExecutionTime. I am reopening the issue and will take a look at this.
A new test was introduced to handle this case.
Thanks!

**Comment by jmrozanec** [comment]
@michaelknigge Issue fixed!
