### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Pitel** [jmrozanec/cron-utils#286]
```kotlin
private val CRON = CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX))
```

```
11-24 14:57:48.106 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: cz.dobrapece, PID: 30241
                                     java.lang.NoSuchMethodError: No static method comparingInt$$STATIC$$(Ljava/util/function/ToIntFunction;)Ljava/util/Comparator; in class Ljava/util/Comparator; or its super classes (declaration of 'java.util.Comparator' appears in /system/framework/core-oj.jar)
                                         at com.cronutils.model.field.definition.FieldDefinition.createFieldDefinitionComparator(FieldDefinition.java:85)
                                         at com.cronutils.model.definition.CronDefinitionBuilder.instance(CronDefinitionBuilder.java:165)
                                         at com.cronutils.model.definition.CronDefinitionBuilder.unixCrontab(CronDefinitionBuilder.java:276)
                                         at com.cronutils.model.definition.CronDefinitionBuilder.instanceDefinitionFor(CronDefinitionBuilder.java:291)
                                         at cz.dobrapece.PlansFragment.<clinit>(PlansFragment.kt:34)
                                         at cz.dobrapece.ClientDetailFragment$onViewCreated$2$1.getItem(ClientDetailFragment.kt:61)
                                         at android.support.v4.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:102)
                                         at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1152)
                                         at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:663)
                                         at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
                                         at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:606)
                                         at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2170)
                                         at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1165)
                                         at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1158)
                                         at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1128)
                                         at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1427)
                                         at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1537)
                                         at android.view.View$PerformClick.run(View.java:22429)
                                         at android.os.Handler.handleCallback(Handler.java:751)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6320)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

Running on Android 7.1.1 (Chromebook)

**Comment by jmrozanec** [comment]
@Pitel thank you for reporting this! Which version of Android do you use? May we ask you for a test? Thanks!

**Comment by Pitel** [comment]
Android 7.1.1. Yes, you can send me a test.

**Comment by jmrozanec** [comment]
@Pitel thanks! If you have a test to reproduce the issue, we will be glad to merge into master. Thanks!

**Comment by Pitel** [comment]
You mean like test project? I don't think it's necessary. The [`comparingInt`](https://developer.android.com/reference/java/util/Comparator.html#comparingInt(java.util.function.ToIntFunction<?%20super%20T>)) method you're using is available since Android 6 (API 24, first version which support Java 8). So the test would be asi simple as:
1. Start Android Studio
2. Create new project with `minSdk` < 24
3. Add `CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX)` to any valid lociation in the project (e. g. inside 'OnCreateView` method)
4. Start the app on any Android device (or emulator) with Android version < 6.0
5. Boom! Crash!

IMO the only possible solution is to rewrite it not using any Java 8 methods (but for example lambdas are possible, but streams are not)

**Comment by jmrozanec** [comment]
Yes, we understand that. From release 7.0.0 we support Android 24+ If using earlier Android versions, please consider using an earlier cron-utils release (6.x.y)

**Comment by Pitel** [comment]
Fair enough :)

Maybe this information should be mentioned in README or somewhere more visible.

**Comment by jmrozanec** [comment]
@Pitel done! Thank you for the suggestion!
