### ISSUE TITLE
"3/4 5/6 7/8 9/2 10/2 ? 2017/2" throws UnknownFormatConversionException

### ISSUE THREAD

**Issue by Naxos84** [jmrozanec/cron-utils#300]
```java
public class TestDescriptor {

    // SoM MoH HoD D0M MoY  DoW Year
    // 3/4 5/6 7/8 9/2 10/2 ?   2017/2

    //Every 4 seconds starting at second 03,
    //every 6 minutes starting at minute :05,
    //every 8 hours starting at 07am,
    //every 2 days starting on the 9th,
    //every 2 months starting in October,
    //every 2 years starting in 2017
    @Test
    public void testFull() {
        final CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        final CronParser parser = new CronParser(cronDefinition);
        final Cron cron = parser.parse("3/4 5/6 7/8 9/2 10/2 ? 2017/2");
        System.out.println(CronDescriptor.instance().describe(cron));
    }

}
```

When running this I get the following Exception.

`java.util.UnknownFormatConversionException: Conversion = 'p'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.cronutils.descriptor.CronDescriptor.describeYear(CronDescriptor.java:152)
	at com.cronutils.descriptor.CronDescriptor.describe(CronDescriptor.java:69)
	at com.cronutils.utils.descriptor.TestDescriptor.testFull(TestDescriptor.java:28)
	..........(skipped the rest)
`

The problem seems when describing the year.

String.format is called with `"every 2%p"`, `["year"]`

**Comment by jmrozanec** [comment]
@Naxos84 closed! Kudos to @pangyikhei!
