### ISSUE TITLE
Parser crashes when adding a range without values

### ISSUE THREAD

**Issue by NielsDoucet** [jmrozanec/cron-utils#369]
The following testcase illustrates the issue:
```
	public static void main(String[] args) {
		validateExpression(CronType.SPRING, "- * * * * ?");
	}

	private static void validateExpression(CronType cronType, String expression) {
		CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(cronType);
		CronParser parser = new CronParser(cronDefinition);
		try {
			System.out.println("Validating expression: " + expression + " using " + cronType + " definition");
			parser.parse(expression);
			System.out.println("this shouldn't be valid!");
		} catch (IllegalArgumentException e) {
			System.out.println("expected failure: " + e.getMessage());
		}
	}
```
This generates the following output
```
Validating expression: - * * * * ? using SPRING definition
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.cronutils.parser.FieldParser.parse(FieldParser.java:86)
	at com.cronutils.parser.CronParserField.parse(CronParserField.java:82)
	at com.cronutils.parser.CronParser.parse(CronParser.java:123)
```

**Comment by jmrozanec** [comment]
@NielsDoucet thank you for reporting this. Don't you mind sending a PR with a test for it? Will check for a solution asap. Thanks! 😄
