### ISSUE TITLE
ArrayIndexOutOfBoundsException instead of IllegalArgumentException

### ISSUE THREAD

**Issue by fi3te** [jmrozanec/cron-utils#412]
Hi,

cronParser.parse("0 0 0 ? * #") throws an ArrayIndexOutOfBoundsException instead of an IllegalArgumentException.

java.lang.ArrayIndexOutOfBoundsException: length=0; index=1
        at com.cronutils.parser.FieldParser.parseOnWithHash(FieldParser.java:185)
        at com.cronutils.parser.FieldParser.parseOn(FieldParser.java:166)
        at com.cronutils.parser.FieldParser.noSpecialCharsNorStar(FieldParser.java:143)
        at com.cronutils.parser.FieldParser.parse(FieldParser.java:79)
        at com.cronutils.parser.CronParserField.parse(CronParserField.java:89)
        at com.cronutils.parser.CronParser.parse(CronParser.java:127)

Best regards,
Fiete

PS: 'com.cronutils:cron-utils:9.0.2'

**Comment by jmrozanec** [comment]
@fi3te a new version was released with the fixes. Please find details [here](https://github.com/jmrozanec/cron-utils/releases/tag/9.1.0) Thank you for contributing to cron-utils!
