### ISSUE TITLE
Invalid validation for sunday and/or invalid calculations

### ISSUE THREAD

**Issue by Haarolean** [jmrozanec/cron-utils#480]
Hi again!

I've encountered a problem: I'm trying to calculate next weekly launches on a sunday. 
Tried to do it like this (now = ZonedDateTime, getValue returns the value from 1 to 7):
```
.withDoW(on(now.getDayOfWeek().getValue()))
```
Turns out it accepts values from 0 to 6:
```
java.lang.IllegalArgumentException: Value 7 not in range [0, 6]
        at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.isInRange(ValidationFieldExpressionVisitor.java:153)
        at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:121)
        at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:66)
        at com.cronutils.model.field.expression.FieldExpression.accept(FieldExpression.java:46)
        at com.cronutils.builder.CronBuilder.addField(CronBuilder.java:94)
        at com.cronutils.builder.CronBuilder.withDoW(CronBuilder.java:70)
```

Which is okay I guess, so I tried this (ordinal -- 0 to 6)
```
.withDoW(on(now.getDayOfWeek().ordinal()))
```
And it doesn't work either!

```
Now: 2021-06-27T03:00+03:00[Europe/Moscow]
now + 1 week: 2021-07-04T03:00+03:00[Europe/Moscow]
nextRun: 2021-07-03T03:00+03:00[Europe/Moscow]
```
This date is wrong by one (saturday instead of sunday).

Am I doing something wrong or is there a bug? I'm gonna submit a test to show how it works for me.

**Comment by jmrozanec** [comment]
@Haarolean thank you for reporting this. We will review it over the week and come back with an answer 😄 Best!

**Comment by IndeedSi** [comment]
Hi, @Haarolean  

The cron definition didn't define valid range for DoW value. That's why it was causing
```
IllegalArgumentException: Value 7 not in range [0, 6]
```

I added 
```
.withDayOfWeek().withValidRange(1, 7).withMondayDoWValue(1).supportsQuestionMark().and()
```
And that fixed the problem here.
I submitted a PR to fix your test case. Please take a look. Thanks!


As for the ordinal 0-6, Sunday is mapped to 6 in this case. But the default definition assume `MondayDoWValue` is 1, that's why 6 is mapped to Saturday. So if you set `.withMondayDoWValue(0)` for this setting, the test could also pass.
Let me know if you have any further questions.
