### ISSUE TITLE
Exception when set DoW as Sunday using QUARTZ definition

### ISSUE THREAD

**Issue by robsoncassol** [jmrozanec/cron-utils#508]
In order to verify the problem, replace the day of the week to Sunday on the following test 
https://github.com/jmrozanec/cron-utils/blob/0759550fa7a18067a0decd5953acd4165f0bf0ab/src/test/java/com/cronutils/model/definition/CronDefinitionBuilderTest.java#L177

**Comment by robsoncassol** [comment]
Stacktrace 

`java.lang.IllegalArgumentException: Value 8 not in range [1, 7]

	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.isInRange(ValidationFieldExpressionVisitor.java:128)
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:95)
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:25)
	at com.cronutils.model.field.expression.On.accept(On.java:70)
	at com.cronutils.builder.CronBuilder.addField(CronBuilder.java:91)
	at com.cronutils.builder.CronBuilder.withDoW(CronBuilder.java:64)
	at biz.te2.services.experiencemanager.util.CronScheduleBuilderTest.testDoWProperWeekdayOffset(CronScheduleBuilderTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
`

**Comment by jmrozanec** [comment]
@robsoncassol thank you for reporting this! May we ask you to provide a PR with a test for this issue? Thanks! 😄

**Comment by sirsha-chatterjee** [comment]
Hi @jmrozanec can I take this up?

**Comment by jmrozanec** [comment]
@sirsha-chatterjee yes, please! 😄 Thanks!

**Comment by jmrozanec** [comment]
@robsoncassol @sirsha-chatterjee  release 9.1.7 was published! Thanks! 😄
