### ISSUE TITLE
IllegalArgumentException when trying to parse `@monthly` nickname

### ISSUE THREAD

**Issue by J0B10** [jmrozanec/cron-utils#522]
# Bug description
When trying to parse cron expression `@monthly` using the Cron parser the following exception occurs:
```
Caused by: java.lang.IllegalArgumentException: Cron expression contains 1 parts but we expect one of [5]
	at com.cronutils.parser.CronParser.parse(CronParser.java:150)
	at org.betonquest.betonquest.api.schedule.CronSchedule.<init>(CronSchedule.java:93)
	... 71 more
```

The following Cron definition was used:
```java
    /**
     * The unix cron syntax with support for nicknames
     */
    public static final CronDefinition DEFAULT_CRON_DEFINITION = CronDefinitionBuilder.defineCron()
            .withMinutes().withValidRange(0, 59).withStrictRange().and()
            .withHours().withValidRange(0, 23).withStrictRange().and()
            .withDayOfMonth().withValidRange(1, 31).withStrictRange().and()
            .withMonth().withValidRange(1, 12).withStrictRange().and()
            .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0).withStrictRange().and()
            .withSupportedNicknameYearly().withSupportedNicknameAnnually()
            .withSupportedNicknameMonthly().withSupportedNicknameWeekly()
            .withSupportedNicknameMidnight().withSupportedNicknameDaily()
            .withSupportedNicknameHourly()
            .instance();
```
And the following code can be used to reproduce it:
```java
new CronParser(DEFAULT_CRON_DEFINITION ).parse("@monthly");
```

## Expected Behaviour
The parser should correctly parse `@monthly`, throwing no exceptions and returning the same cron as defined by `0 0 1 * *`.

-----------
_I'll look into creating a pull request with unit tests and a fix_

**Comment by jmrozanec** [comment]
@J0B10 thanks! We will appreciate that! 😄 If can be extended to the rest of the aliases, it would be great 😄
