### ISSUE TITLE
RuntimeException / UnknownFormatConversionException (Conversion = 'p')

### ISSUE THREAD

**Issue by SeaLife** [jmrozanec/cron-utils#60]
Hi,

like in Issue #32  i got an 'java.util.UnknownFormatConversionException: Conversion = 'p'' error.

Log:

```
14 Dez 2015 10:03:42.452 [Thread-86] INFO  de.*.*.cron.QueryManager - Starting Process-Protector...
14 Dez 2015 10:03:42.472 [Thread-87] INFO  de.*.*.cron.QueryManager - Adding Query: 'Test'
14 Dez 2015 10:03:42.513 [Thread-87] DEBUG de.*.*.cron.QueryManager - QUARTZ CRON: 0 * * ? * 1,5
14 Dez 2015 10:03:42.526 [Thread-87] DEBUG de.*.*.cron.QueryManager - IsValid?: true
java.util.UnknownFormatConversionException: Conversion = 'p'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2646)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2675)
	at java.util.Formatter.parse(Formatter.java:2528)
	at java.util.Formatter.format(Formatter.java:2469)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2792)
	at com.cronutils.descriptor.CronDescriptor.describeDayOfWeek(CronDescriptor.java:121)
	at com.cronutils.descriptor.CronDescriptor.describe(CronDescriptor.java:63)
	at de.*.*.cron.QueryManager.scheduleTask(QueryManager.java:99)
	at de.*.*.cron.QueryManager.add(QueryManager.java:62)
	at de.*.*.cron.QueryManager$2.run(QueryManager.java:201)
	at java.lang.Thread.run(Thread.java:745)
14 Dez 2015 10:03:42.586 [Thread-87] FATAL de.*.*.cron.QueryManager - Getting RuntimeException! Conversion = 'p'
[2015-12-14 10:03:42,971] Artifact RQT: Artifact is deployed successfully
[2015-12-14 10:03:42,971] Artifact RQT: Deploy took 2.688 milliseconds
```

Code:

```java
CronDefinition definition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
CronParser parser = new CronParser(definition);
CronValidator validator = new CronValidator(definition);
log.debug("QUARTZ CRON: " + query.getProperties().getProperty(QueryProperties.TIME));
log.debug("IsValid?: " + validator.isValid(query.getProperties().getProperty(QueryProperties.TIME)));
Cron c = parser.parse(query.getProperties().getProperty(QueryProperties.TIME));
String Description = CronDescriptor.instance(Locale.GERMAN).describe(c);
log.debug(Description);
```

ivy.xml
```xml
<ivy-module version="2.0">
	<info organisation="org.apache" module="RepeatedQueryTool"/>
	<dependencies>
		<dependency org="commons-lang" name="commons-lang" rev="2.0"/>
		<dependency org="commons-cli" name="commons-cli" rev="1.0"/>
		<dependency org="commons-codec" name="commons-codec" rev="1.10"/>
		<dependency org="com.google.guava" name="guava" rev="18.0"/>
		<dependency org="org.apache.logging.log4j" name="log4j-api" rev="2.3"/>
		<dependency org="org.apache.logging.log4j" name="log4j-core" rev="2.3"/>
		<dependency org="org.apache.logging.log4j" name="log4j-web" rev="2.3"/>
		<dependency org="net.redhogs.cronparser" name="cron-parser-core" rev="2.8"/>
		<dependency org="com.cronutils" name="cron-utils" rev="3.1.2"/>
		<dependency org="org.apache.httpcomponents" name="httpclient" rev="4.5.1"/>
		<dependency org="commons-io" name="commons-io" rev="2.4"/>
		<dependency org="com.googlecode.json-simple" name="json-simple" rev="1.1.1"/>

		<dependency org="org.quartz-scheduler" name="quartz" rev="2.2.1">
			<exclude org="javax.servlet" name="servlet-api"/>
			<exclude org="javax.servlet" name="jsp-api"/>
			<exclude org="javax.*"/>
			<exclude type="src"/>
		</dependency>

		<dependency org="org.slf4j" name="slf4j-nop" rev="1.7.12">
			<exclude org="javax.servlet" name="servlet-api"/>
			<exclude org="javax.servlet" name="jsp-api"/>
			<exclude org="javax.*"/>
		</dependency>

		<dependency org="org.json" name="json" rev="20140107">
			<exclude org="javax.servlet" name="servlet-api"/>
			<exclude org="javax.servlet" name="jsp-api"/>
			<exclude org="javax.*"/>
		</dependency>

		<exclude org="javax.servlet"/>
		<exclude org="javax.*"/>
	</dependencies>
</ivy-module>
```

Used CRON Expression: 0 * * ? * 1,5

Tested & Buggy with: 3.1.0, 3.1.2

Greets
SeaLife

**Comment by jmrozanec** [comment]
@SeaLife thank you for reporting this. Contributions are always welcome!

**Comment by vtico** [comment]
I've change the code to avoid the exception and send a pull request.

**Comment by jmrozanec** [comment]
Fixed with contributed pull request! Thank you for contributing a solution!
