### ISSUE TITLE
Cannot map day of week (5#1)

### ISSUE THREAD

**Issue by alexey-anufriev** [jmrozanec/cron-utils#605]
It is not possible to perform the following mapping:

```java
CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.SPRING);
CronParser cronParser = new CronParser(cronDefinition);
Cron cron = cronParser.parse("0 0 0 ? * 5#1");
CronMapper mapper = CronMapper.fromSpringToQuartz();
Cron quartzCron = mapper.map(cron);
```

Execution leads to the following exception:

```
java.lang.IllegalArgumentException: value missing for a#b cron expression

	at com.cronutils.utils.Preconditions.checkArgument(Preconditions.java:110)
	at com.cronutils.model.field.expression.On.<init>(On.java:43)
	at com.cronutils.mapper.CronMapper$1.visit(CronMapper.java:294)
	at com.cronutils.model.field.expression.On.accept(On.java:70)
	at com.cronutils.mapper.CronMapper.lambda$dayOfWeekMapping$5(CronMapper.java:288)
	at com.cronutils.mapper.CronMapper.map(CronMapper.java:88)
```

**Comment by jmrozanec** [comment]
@alexey-anufriev may we ask you for a PR with the corresponding test? Thanks!

**Comment by alexey-anufriev** [comment]
Sure, https://github.com/jmrozanec/cron-utils/pull/606

**Comment by alexey-anufriev** [comment]
hi @jmrozanec, any plans for release?

**Comment by jmrozanec** [comment]
@alexey-anufriev yes, we are cleansing everything to release by the end of June.

**Comment by goforabhishek** [comment]
Hi @jmrozanec ,
Is there a plan to release it? We have this issue unsolved yet!
