### ISSUE TITLE
Invalid Exception on cron: 0 0 12 1W * ? *

### ISSUE THREAD

**Issue by DanoOM** [jmrozanec/cron-utils#75]
The above expression (Quartz) should return the first workday of the month.  (i.e. the one closest to the '1st').

Instead an exception is thrown when calling nextExecution

java.lang.IllegalArgumentException: Values must not be empty
	at org.apache.commons.lang3.Validate.notEmpty(Validate.java:300)
	at com.cronutils.model.time.TimeNode.<init>(TimeNode.java:31)
	at com.cronutils.model.time.ExecutionTime.generateDays(ExecutionTime.java:320)
	at com.cronutils.model.time.ExecutionTime.nextClosestMatch(ExecutionTime.java:169)
	at com.cronutils.model.time.ExecutionTime.nextExecution(ExecutionTime.java:123)
	at com.cronutils.model.time.ExecutionTimeQuartzIntegrationTest.testCronWithFirstWorkDayOfWeek(ExecutionTimeQuartzIntegrationTest.java:326)

Test pull-request coming..

**Comment by jmrozanec** [comment]
@DanoOM Thank you for fixing this! Will soon release a version with it.

**Comment by jmrozanec** [comment]
@DanoOM New version released! Please check details [here](https://github.com/jmrozanec/cron-utils/releases/tag/4.0.0)
